const keyMirror = require('react/lib/keyMirror');

module.exports = keyMirror({

  SOURCE_VIEW_ACTION: null,
  SOURCE_SERVER_ACTION: null,
  SOURCE_ROUTER_ACTION: null,
  PRODUCT_DETAIL: null,
  GOT_FRIENDS: null,
  FETCH: null,
  LIKE: null,
  UNLIKE: null,
  LOGOUT: null,
  LOGIN: null,
  CHANGE_EVENT: null,
  EMIT_CHANGE: null,
  AUTHENTICATION: null,
  AUTH_FAIL: null,
  AUTHENTICATED: null,
  AUTHORIZED: null,
  LIKE_CREATED: null,
  NEW_DATA: null,
  SAVE_SELL_FORM: null,
  GOT_PRODUCTS_SELL_BY_USER: null,
  NEW_PAYMENT: null,
  NEW_SHIPPING: null,
  SAVE_IMAGE: null,
  CROP_IMAGE: null,
  PRODUCT_LAUNCH: null,
  GOT_ORDER: null,
  GOT_MESSAGE: null,
  GOT_ORDER_MESSAGE: null,
  GOT_CHAT: null,
  GOT_USER_PROFILE: null,
  GOT_PRODUCTS: null,
  GOT_PRODUCT: null,
  GOT_PRODUCTS_RELATED: null,
  TOGGLE_FOLLOW: null,
  TOGGLE_LIKE: null,
  SEND_MSG: null,
  SENT_MSG: null,
  REFRESH: null,
  SIGNUP: null,
  SIGNUP_ERROR: null,
  SAVE_VIDEO: null,
  LOGGED: null,
  GOT_ALL_USERS: null,
  DELETE_PAYMENT: null,
  DELETE_SHIPPING: null,
  GOT_VIDEO_PRODUCTS: null,
  GOT_COMMENTS: null,
  SEND_COMMENT: null,
  GOT_FOLLOWS: null,
  GOT_FANS: null,
});
